Numpy


Importing Numpy

In [2]:
import numpy as np

Basics of Numpy

Arrays

Array is a structure for storing and retrieving data. A grid in place, with each cell storing an element.


All elements of the array must be of the same type of data.

Once created, the total size of the array can’t change.

The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [9]:
a = np.array([1, 2, 3, 4, 5, 6]) #creating one-dimensional array

In [3]:
a[0]

1

In [10]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

all selected data refers to the original array, even if it is saved in other variable

In [13]:
b = a[3:] 
print(b)
b[0] = 100
print(a)

[100   5   6]
[ 10   2   3 100   5   6]


Two and higher dimensional arrays can be initialized from nested Python sequences

In [14]:
two_dimensional_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
two_dimensional_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Selecting data from high dimensional arrays

In [18]:
two_dimensional_array[2,3]

12

Array Attribute

In [19]:
two_dimensional_array.ndim #The dimensional level of arrays are contained by the ndim attribute

2

In [23]:
print(two_dimensional_array.shape) #The shape of an array is the accorded to the number of datas contained in each dimension
print(np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]).shape)
#The most outer bracket included 2 second dimension bracket and inside each two dimension bracket there is 3 third dimension bracket and 4 numeric data inside them therefore the shape is (2,3,4)

(3, 4)
(2, 3, 4)


In [24]:
two_dimensional_array.size #The count of most inner data is stored in size, and the size of any created array is fixed

12

In [26]:
import math
two_dimensional_array.size == math.prod(two_dimensional_array.shape) #The size of an array is always equals to the product(multiply) of the numbers of the array's shape.

True

In [27]:
two_dimensional_array.dtype #Arrays are typically "homogeneous" meaning that they contain element of only one datatype

dtype('int32')

Create Basic Arrays

In [28]:
np.zeros(2) #Create an array that containes all zero value

array([0., 0.])

In [30]:
np.ones(shape = (2,2)) #Create an array that containes all one value

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.empty(2) #The function empty creates an array whose initial content is random and depends on the state of the memory. 
#The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [33]:
np.arange(4) #Range function but in array form

array([0, 1, 2, 3])

In [34]:
np.arange(2,9,2) #Start, stop and step can be used in arange too

array([2, 4, 6, 8])

In [37]:
np.linspace(0,10, num=5) #np.linspace() to create an array with values that are spaced linearly in a specified interval, num is to specify the count of numbers inclued

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
x = np.ones(2, dtype=np.str0) # While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.
x

array(['1', '1'], dtype='<U1')

Adding, Removing, and Sorting Elements

In [41]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8]) #array used in this section
np.sort(arr) #sort values in ascending order

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b)) #Group two arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
multi_dimension_in_sort = np.array([[[2, 2, 3, 4], [5, 8, 7, 8], [9, 80, 3, 12]],
                [[13, 1, 15, 16], [9, 2, 19, 20], [30, 12, 16, 4]]])
np.sort(multi_dimension_in_sort) #sort value in their own group

array([[[ 2,  2,  3,  4],
        [ 5,  7,  8,  8],
        [ 3,  9, 12, 80]],

       [[ 1, 13, 15, 16],
        [ 2,  9, 19, 20],
        [ 4, 12, 16, 30]]])

Reshape an Array

In [51]:
np.arange(6).reshape(2,3) # Can only be reshape if the size of the specified shape array is the same as the original array

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
reshape_array = np.arange(6)
np.reshape(reshape_array, newshape=(2,3), order='C') #You can also specify the index order type of the new array. C refers to C-type index order and F refers to Fortran-like index order. C: [0,1,2,3,4], F:[1,2,3,4,5]

array([[0, 1, 2],
       [3, 4, 5]])

Convert 1D array to 2D array

In [9]:
con = np.array([1,2,3,4,5,6])
con.shape

array([1, 2, 3, 4, 5, 6])

In [4]:
con2 = con[np.newaxis, :] #adding a new axis to the array
con2.shape

(1, 6)

In [6]:
row_vector = con[np.newaxis, :]
row_vector.shape

(1, 6)

In [10]:
column_vector = con[:,np.newaxis]
column_vector.shape

(6, 1)

In [12]:
new_dimension = np.arange(1,7)
new_dimension.shape

(6,)

In [15]:
new_dimension1 = np.expand_dims(new_dimension, axis=1)
new_dimension.shape

(6,)

In [16]:
new_dimension2 = np.expand_dims(new_dimension, axis=0)
new_dimension2.shape

(1, 6)

Indexing and Slicing

In [17]:
slicing = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
slicing

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
slicing[slicing<5]

array([1, 2, 3, 4])

In [22]:
five_up = (slicing>=5)
slicing[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
np.concatenate((slicing[(slicing>2)&(slicing<11)],slicing[(slicing>=2)|(slicing<=11)])) #logical operator is replaced by &(and) or |(or)

array([ 3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12])

In [29]:
five_up = (slicing > 5) | (slicing == 5) #Can be used to return boolean values
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [31]:
slicing_non_zero = np.nonzero(slicing>5) #return 1*dimension number array and each array refers to the corresponding dimension's index.
print(slicing_non_zero)
#using the above code as example the index place of non-zero value is [1,1], [1,2], [1,3], [2,0], [2,1], [2,2], [2,3]

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3], dtype=int64))


Creating Array from Existing Data

In [32]:
existing_data = np.arange(1,11)
existing_data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
new1 = existing_data[3:8] # You can create new array by slicing existing array
new1

array([4, 5, 6, 7, 8])

In [34]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2)) #stack two array vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [35]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

In [ ]:
np.hsplit(x, 3) # Split this array into three equally shaped arrays

In [ ]:
np.hsplit(x, (3,4)) # Split column from 1-3, 4 and the rest

Basic array operations

In [47]:
a = np.array([1,2])
b = np.ones(2, dtype=int)
a,b

(array([1, 2]), array([1, 1]))

In [43]:
print(a+b) #(1+1), (2+1)
print(a-b) #(1-1), (2-1)
print(a*a) #(1*1), (2*2)
print(a/a) #(1/1), (2/1) 

[2 3]
[0 1]
[1 4]
[1. 1.]


In [45]:
a = np.array([1,2,3,4])
a.sum() #to find the sum of all the value in array, works for higher dimensional array too

10

In [48]:
a * 1.6 # Broadcasting, operation between an array and a single number

array([1.6, 3.2])

More Operations

In [49]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.max()) # Maximum Value
print(a.min()) # Minimum Value
print(a.sum()) # Sum of all Value
print(a.mean()) # Average of all value
print(a.prod()) # Result of Multiplying the Value
print(a.std()) #Standard Deviation

10
1
55
5.5
3628800
2.8722813232690143


In [51]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones = np.array([1, 1]) 
data + ones

array([[2, 3],
       [4, 5],
       [6, 7]])

Generate Numbers

In [56]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.08656445, 0.73571058, 0.79640257])

In [57]:
rng.integers(5, size=(2, 4)) 

array([[4, 3, 0, 1],
       [3, 3, 0, 3]], dtype=int64)

Get Unique Items and Count

In [58]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a) # Return an Array Containing only Non-Repeating Value 
print(unique_values)
unique_values, indices_list = np.unique(a, return_index=True) # Returning the Array and Index of Them in the Original List
print(indices_list)
unique_values, occurrence_count = np.unique(a, return_counts=True) # Returning the Array and Occurent Count
print(occurrence_count)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]


In [59]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d) # Works with 2D arrays too  
print(unique_values)
unique_rows = np.unique(a_2d, axis=0) # When axis is specified the array will not be flatten
print(unique_rows)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Transpose an Array

In [60]:
arr = np.arange(6).reshape((2, 3))
print(arr)
print(arr.transpose()) # To reverse the shape
print(arr.T) # Short form of transpose

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


Reverse an Array

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [63]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d) 
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0) # Reverse only the rows
reversed_arr_rows

In [ ]:
reversed_arr_column = np.flip(arr_2d, axis=1) # Reverse only the columns
print(reversed_arr_column)

In [64]:
arr_2d[1] = np.flip(arr_2d[1]) # Specify the row to reverse
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1]) # Specify the column to reverse
arr_2d