Numpy


Importing Numpy

In [1]:
import numpy as np

Basics of Numpy

Arrays

Array is a structure for storing and retrieving data. A grid in place, with each cell storing an element.


All elements of the array must be of the same type of data.

Once created, the total size of the array can’t change.

The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [9]:
a = np.array([1, 2, 3, 4, 5, 6]) #creating one-dimensional array

In [3]:
a[0]

1

In [10]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

all selected data refers to the original array, even if it is saved in other variable

In [13]:
b = a[3:] 
print(b)
b[0] = 100
print(a)

[100   5   6]
[ 10   2   3 100   5   6]


Two and higher dimensional arrays can be initialized from nested Python sequences

In [14]:
two_dimensional_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
two_dimensional_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Selecting data from high dimensional arrays

In [18]:
two_dimensional_array[2,3]

12

Array Attribute

In [19]:
two_dimensional_array.ndim #The dimensional level of arrays are contained by the ndim attribute

2

In [23]:
print(two_dimensional_array.shape) #The shape of an array is the accorded to the number of datas contained in each dimension
print(np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]).shape)
#The most outer bracket included 2 second dimension bracket and inside each two dimension bracket there is 3 third dimension bracket and 4 numeric data inside them therefore the shape is (2,3,4)

(3, 4)
(2, 3, 4)


In [24]:
two_dimensional_array.size #The count of most inner data is stored in size, and the size of any created array is fixed

12

In [26]:
import math
two_dimensional_array.size == math.prod(two_dimensional_array.shape) #The size of an array is always equals to the product(multiply) of the numbers of the array's shape.

True

In [27]:
two_dimensional_array.dtype #Arrays are typically "homogeneous" meaning that they contain element of only one datatype

dtype('int32')

Create Basic Arrays

In [28]:
np.zeros(2) #Create an array that containes all zero value

array([0., 0.])

In [30]:
np.ones(shape = (2,2)) #Create an array that containes all one value

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.empty(2) #The function empty creates an array whose initial content is random and depends on the state of the memory. 
#The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [33]:
np.arange(4) #Range function but in array form

array([0, 1, 2, 3])

In [34]:
np.arange(2,9,2) #Start, stop and step can be used in arange too

array([2, 4, 6, 8])

In [37]:
np.linspace(0,10, num=5) #np.linspace() to create an array with values that are spaced linearly in a specified interval, num is to specify the count of numbers inclued

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
x = np.ones(2, dtype=np.str0) # While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.
x

array(['1', '1'], dtype='<U1')

Adding, Removing, and Sorting Elements

In [41]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8]) #array used in this section
np.sort(arr) #sort values in ascending order

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b)) #Group two arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
multi_dimension_in_sort = np.array([[[2, 2, 3, 4], [5, 8, 7, 8], [9, 80, 3, 12]],
                [[13, 1, 15, 16], [9, 2, 19, 20], [30, 12, 16, 4]]])
np.sort(multi_dimension_in_sort) #sort value in their own group

array([[[ 2,  2,  3,  4],
        [ 5,  7,  8,  8],
        [ 3,  9, 12, 80]],

       [[ 1, 13, 15, 16],
        [ 2,  9, 19, 20],
        [ 4, 12, 16, 30]]])

Reshape an Array

In [51]:
np.arange(6).reshape(2,3) # Can only be reshape if the size of the specified shape array is the same as the original array

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
reshape_array = np.arange(6)
np.reshape(reshape_array, newshape=(2,3), order='C') #You can also specify the index order type of the new array. C refers to C-type index order and F refers to Fortran-like index order. C: [0,1,2,3,4], F:[1,2,3,4,5]

array([[0, 1, 2],
       [3, 4, 5]])